-- MySQL Script generated by MySQL Workbench
-- qua 21 nov 2018 19:11:24 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `petshop` ;

-- -----------------------------------------------------
-- Schema petshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petshop` ;
USE `petshop` ;

-- -----------------------------------------------------
-- Table `petshop`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`produtos` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `imagem` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id_produtos`),
  UNIQUE INDEX `id_produtos_UNIQUE` (`id_produtos` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `type` SMALLINT(6) NOT NULL,
  `remenber_token` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_datarar` TIMESTAMP NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `id_users_UNIQUE` (`id_users` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petshop`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop`.`compras` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `produtos_id_produtos` INT NOT NULL,
  `users_id_users` INT NOT NULL,
  `quantidade` SMALLINT(6) NOT NULL,
  `data` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id_compras`),
  UNIQUE INDEX `id_compras_UNIQUE` (`id_compras` ASC),
  INDEX `fk_compras_produtos_idx` (`produtos_id_produtos` ASC),
  INDEX `fk_compras_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_compras_produtos`
    FOREIGN KEY (`produtos_id_produtos`)
    REFERENCES `petshop`.`produtos` (`id_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `petshop`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
